spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://jvg856d6.2277.dnstoo.com:5511/kuaiyuntest
    username: kuaiyuntest_f
    password: piao
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


